% -------------------------------------------------------------------
%  Generated by MATLAB on 31-Jul-2024 19:35:40
%  MATLAB version: 9.13.0.2049777 (R2022b)
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

c = saveVarsMat.c; % <1x19200 double> too many elements

cA = saveVarsMat.cA; % <30x40 double> too many elements

cD = saveVarsMat.cD; % <30x40 double> too many elements

cH = saveVarsMat.cH; % <30x40 double> too many elements

cV = saveVarsMat.cV; % <30x40 double> too many elements

imG = saveVarsMat.imG; % <120x160 uint8> too many elements

img = saveVarsMat.img; % <120x160x3 uint8> too many elements

imgGray = saveVarsMat.imgGray; % <120x160 uint8> too many elements

nWavelets = 4;

num_scales = 4;

reconstructedImg = saveVarsMat.reconstructedImg; % <120x160 double> too many elements

s = ...
  [30 40;
   30 40;
   60 80;
   120 160];

waveletFunction = 'haar';

clear saveVarsMat;
